### ISSUE TITLE
Cannot convert value of type 'RoomObjectAnchor' to expected argument type 'AnchoringComponent.Target'

### ISSUE THREAD

**Issue by mangorui** [jmousseau/RoomObjectReplicator#1]
I cloned this demo(RoomObjectReplicatorDemo),  but there were 74 error prompts when building the project, like:

/.../RoomObjectReplicatorDemo-dsjfhqkqzvqzthcbetoqtqeuelgb/SourcePackages/checkouts/RoomObjectReplicator/Sources/RoomObjectReplicator/RoomObjectSystem.swift:48:44: error build: Cannot convert value of type 'RoomObjectAnchor' to expected argument type 'AnchoringComponent.Target'

   /Users/.../RoomObjectReplicatorDemo-dsjfhqkqzvqzthcbetoqtqeuelgb/SourcePackages/checkouts/RoomObjectReplicator/Sources/RoomObjectReplicator/RoomObjectSystem.swift:55:47: error build: Cannot infer contextual base in reference to member 'systemYellow'

/Users/.../RoomObjectReplicatorDemo-dsjfhqkqzvqzthcbetoqtqeuelgb/SourcePackages/checkouts/RoomObjectReplicator/Sources/RoomObjectReplicator/RoomObjectSystem.swift:124:45: error build: Argument passed to call that takes no arguments

...

Xcode version: 14.0 beta (14A5228q)

**Comment by jmousseau** [comment]
That's strange. I just cloned and successful built the demo with the same Xcode version. May I ask what target you are building the demo for?

**Comment by mangorui** [comment]
I see.  The target I set is iOS simulator(iPhone 13 Pro). It should use 'Any iOS device' to build. and use real machine test  right ?

**Comment by mangorui** [comment]
Tested with a real device it worked fine.  thanks for your response.

**Comment by jmousseau** [comment]
No problem, glad you are unblocked!
