### ISSUE TITLE
Would it be possible to provide some sample code on how to integrate this in a project?

### ISSUE THREAD

**Issue by jordibruin** [jmousseau/RoomObjectReplicator#2]
I came across this while playing around with the RoomPlan API and as someone who is quite new to the whole AR thing this looks super useful. 

However, I'm having a bit of a hard time figuring out how to use this in a regular project.

My goal is to scan a room to save the worldState, and then reload it later together with the ARAnchors that get created through RoomObjectReplicator. Anything you could share to push me in the right direction would be appreciated!

- Jordi

**Comment by jmousseau** [comment]
Jordi,

The [`RoomObjectReplicatorDemo`](https://github.com/jmousseau/RoomObjectReplicatorDemo) project is a good place to start. In order to save the `RoomObjectAnchor` to the world map, you'll need to implement the `NSSecureCoding` protocol. From the `ARAnchor` docs:

> Anchor subclasses must also adopt the [NSSecureCoding](https://developer.apple.com/documentation/foundation/nssecurecoding) protocol. Override [encode(with:)](https://developer.apple.com/documentation/foundation/nscoding/1413933-encode) and [init(coder:)](https://developer.apple.com/documentation/foundation/nscoding/1416145-init) to save and restore the values your subclass' custom properties when ARKit saves and loads them in a world map.

**Comment by jordibruin** [comment]
Thanks so much @jmousseau , I missed that! Appreciate the help!
